### ISSUE TITLE
Does not work with season x replays

### ISSUE THREAD

**Issue by dnpthree** [Shiqan/fortnite-replay-reader#12]
I receive ray.logging:Couldn't parse event PLAYER_ELIMINATION

**Comment by jwalshdev** [comment]
I dug through a bit of the code and realized it is in the reader.py file. There is a statement that checks the current fortnite version and skips ahead based on the version. With the new version, it hits the else statement and raises a PlayerEliminationException. I have tried to replace the raise call with various values for self.replay.skip(x) but have not found a solution.

**Comment by dnpthree** [comment]
Do we need to find the new magic number for season 10 replays? What can I do to help?

**Comment by GauPanisset** [comment]
`if self.header.engine_network_version >= 11 and self.header.branch >= '++Fortnite+Release-9.10':`
This test fail because of the comparaison between strings... Actually `'++Fortnite+Release-9.10'` is greater than `'++Fortnite+Release-10.0'` (which is the current branch version)

So to fix it, I just did the following change : 
`if self.header.engine_network_version >= 11 and (self.header.branch >= '++Fortnite+Release-9.10' or self.header.branch >= '++Fortnite+Release-10.0' ):`

**Comment by dnpthree** [comment]
Worked great. I'll submit a PR

**Comment by dnpthree** [comment]
https://github.com/Shiqan/fortnite-replay-reader/pull/13

**Comment by Shiqan** [comment]
Thanks for the PR @dnpthree. I knew at some point the string comparison would fail 😄 
Added a more future prove solution now.
