### ISSUE TITLE
Latest replays produce "Missing weapon" errors

### ISSUE THREAD

**Issue by stevegee58** [Shiqan/fortnite-replay-reader#22]
Looks like the replays since the recent patch produce a bunch of "Missing weapon type" errors

**Comment by stevegee58** [comment]
I fixed this issue.  Would you like the changes on my own branch or can I push to development?

**Comment by Shiqan** [comment]
Hi @stevegee58 sorry for the late response.
The issue is that Weapons is actually a list of ids, which changes every patch. So the way I wrote it isnt very maintainable. So realistically I should just remove that enum entirely. I'm quite far with actually reading the entire replay in my C# variant. Once that is done I'll make sure to update the Python one as well :) That way, we dont need the Weapons enum anymore since the replay will contain the correct weapon with id.

And just in case, I dont think you can push your changes to my repository. Or even create a branch for that matter. You'd need to fork this repo and make a PR from your forked repo to my development branch. I'd be happy to review and accept any PR of course!

**Comment by stevegee58** [comment]
Actually the weapon errors in this case were because there's a new player type value so the parser got out of sync in the replay file.
I'll fork and do a pull request.  Thanks!
